import type {
  Organization,
  Proposal,
  Client,
  Phase,
} from '@/types/database';

const ORG_ID = 'org_seed_001';
const USER_ID = 'user_seed_001';

export function getSeedOrganization(): Organization {
  return {
    id: ORG_ID,
    name: 'Meridian Experiential',
    slug: 'meridian-experiential',
    logo_url: null,
    favicon_url: null,
    brand_config: {
      primaryColor: '#0f172a',
      secondaryColor: '#3b82f6',
      accentColor: '#6366f1',
      backgroundColor: '#ffffff',
      fontHeading: 'Inter',
      fontBody: 'Inter',
      portalTitle: 'Meridian Experiential',
      companyTagline: 'Experiences that move people.',
      footerText: '© 2026 Meridian Experiential LLC',
    },
    facilities: [
      {
        id: 'fac_001',
        name: 'Meridian HQ',
        city: 'Los Angeles',
        state: 'CA',
        country: 'US',
        type: 'headquarters',
        isHQ: true,
      },
      {
        id: 'fac_002',
        name: 'Meridian Fabrication',
        city: 'Long Beach',
        state: 'CA',
        country: 'US',
        type: 'warehouse',
        isHQ: false,
      },
    ],
    default_payment_terms: {
      structure: '50/50',
      depositPercent: 50,
      balancePercent: 50,
      lateFeeRate: 1.5,
      creditCardSurcharge: 3,
    },
    default_phase_template_id: 'tmpl_001',
    settings: {
      timezone: 'America/Los_Angeles',
      currency: 'USD',
      invoicePrefix: 'MER',
      proposalPrefix: 'MER',
    },
    subscription_tier: 'professional',
    stripe_customer_id: null,
    created_at: '2025-01-15T00:00:00Z',
    updated_at: '2026-03-20T00:00:00Z',
  };
}

export function getSeedClients(): Client[] {
  return [
    {
      id: 'client_001',
      organization_id: ORG_ID,
      company_name: 'Nike',
      industry: 'Sportswear & Apparel',
      billing_address: {
        street: 'One Bowerman Drive',
        city: 'Beaverton',
        state: 'OR',
        zip: '97005',
        country: 'US',
      },
      tags: ['enterprise', 'repeat'],
      source: 'referral',
      _crm_external_ids: null,
      created_at: '2025-02-01T00:00:00Z',
      updated_at: '2026-03-15T00:00:00Z',
    },
    {
      id: 'client_002',
      organization_id: ORG_ID,
      company_name: 'Spotify',
      industry: 'Music & Entertainment',
      billing_address: {
        street: '4 World Trade Center',
        city: 'New York',
        state: 'NY',
        zip: '10007',
        country: 'US',
      },
      tags: ['enterprise', 'tech'],
      source: 'inbound',
      _crm_external_ids: null,
      created_at: '2025-03-10T00:00:00Z',
      updated_at: '2026-03-01T00:00:00Z',
    },
    {
      id: 'client_003',
      organization_id: ORG_ID,
      company_name: 'Mercedes-Benz',
      industry: 'Automotive',
      billing_address: {
        street: 'One Mercedes-Benz Drive',
        city: 'Sandy Springs',
        state: 'GA',
        zip: '30328',
        country: 'US',
      },
      tags: ['enterprise', 'luxury'],
      source: 'trade-show',
      _crm_external_ids: null,
      created_at: '2025-04-20T00:00:00Z',
      updated_at: '2026-02-28T00:00:00Z',
    },
    {
      id: 'client_004',
      organization_id: ORG_ID,
      company_name: 'Apple',
      industry: 'Technology',
      billing_address: {
        street: 'One Apple Park Way',
        city: 'Cupertino',
        state: 'CA',
        zip: '95014',
        country: 'US',
      },
      tags: ['enterprise', 'tech', 'repeat'],
      source: 'referral',
      _crm_external_ids: null,
      created_at: '2025-05-01T00:00:00Z',
      updated_at: '2026-03-25T00:00:00Z',
    },
  ];
}

export function getSeedProposals(): Proposal[] {
  return [
    {
      id: 'prop_001',
      organization_id: ORG_ID,
      client_id: 'client_001',
      name: 'Nike Air Max Experience',
      subtitle: 'Immersive retail pop-up for Air Max Day 2026',
      version: 1,
      status: 'draft',
      current_phase_id: null,
      probability: 40,
      currency: 'USD',
      total_value: 185000,
      total_with_addons: 210000,
      prepared_date: '2026-03-28T00:00:00Z',
      valid_until: '2026-04-28T00:00:00Z',
      source: 'referral',
      narrative_context: {
        brandVoice: 'Bold, athletic, aspirational',
        audienceProfile: 'Sneakerheads and Gen Z consumers',
        experienceGoal: 'Drive Air Max Day engagement and social sharing',
      },
      payment_terms: {
        structure: '50/50',
        depositPercent: 50,
        balancePercent: 50,
      },
      terms_document_id: null,
      tags: ['pop-up', 'retail', 'experiential'],
      portal_access_token: null,
      portal_first_viewed_at: null,
      created_by: USER_ID,
      parent_proposal_id: null,
      phase_template_id: 'tmpl_001',
      created_at: '2026-03-25T00:00:00Z',
      updated_at: '2026-03-28T00:00:00Z',
    },
    {
      id: 'prop_002',
      organization_id: ORG_ID,
      client_id: 'client_002',
      name: 'Spotify Wrapped Pop-Up',
      subtitle: 'Year-end interactive installation in NYC',
      version: 2,
      status: 'sent',
      current_phase_id: 'phase_002_01',
      probability: 65,
      currency: 'USD',
      total_value: 320000,
      total_with_addons: 365000,
      prepared_date: '2026-03-15T00:00:00Z',
      valid_until: '2026-04-15T00:00:00Z',
      source: 'inbound',
      narrative_context: {
        brandVoice: 'Playful, data-driven, personal',
        audienceProfile: 'Music lovers and social media users',
        experienceGoal: 'Create shareable moments celebrating user listening data',
      },
      payment_terms: {
        structure: '40/40/20',
        depositPercent: 40,
        balancePercent: 40,
      },
      terms_document_id: null,
      tags: ['installation', 'interactive', 'seasonal'],
      portal_access_token: 'tkn_spotify_001',
      portal_first_viewed_at: null,
      created_by: USER_ID,
      parent_proposal_id: null,
      phase_template_id: 'tmpl_001',
      created_at: '2026-03-10T00:00:00Z',
      updated_at: '2026-03-15T00:00:00Z',
    },
    {
      id: 'prop_003',
      organization_id: ORG_ID,
      client_id: 'client_003',
      name: 'Mercedes-Benz EQS Launch',
      subtitle: 'Luxury EV launch experience across three cities',
      version: 1,
      status: 'viewed',
      current_phase_id: 'phase_003_01',
      probability: 75,
      currency: 'USD',
      total_value: 485000,
      total_with_addons: 520000,
      prepared_date: '2026-03-01T00:00:00Z',
      valid_until: '2026-04-01T00:00:00Z',
      source: 'trade-show',
      narrative_context: {
        brandVoice: 'Premium, innovative, understated luxury',
        audienceProfile: 'High-net-worth individuals and EV early adopters',
        experienceGoal: 'Position EQS as the pinnacle of electric luxury',
      },
      payment_terms: {
        structure: '50/50',
        depositPercent: 50,
        balancePercent: 50,
      },
      terms_document_id: null,
      tags: ['launch', 'automotive', 'multi-city'],
      portal_access_token: 'tkn_mercedes_001',
      portal_first_viewed_at: '2026-03-05T14:22:00Z',
      created_by: USER_ID,
      parent_proposal_id: null,
      phase_template_id: 'tmpl_001',
      created_at: '2026-02-20T00:00:00Z',
      updated_at: '2026-03-05T00:00:00Z',
    },
    {
      id: 'prop_004',
      organization_id: ORG_ID,
      client_id: 'client_004',
      name: 'Apple Vision Pro Demo Suite',
      subtitle: 'Retail demo experience for Apple Vision Pro',
      version: 3,
      status: 'approved',
      current_phase_id: 'phase_004_03',
      probability: 95,
      currency: 'USD',
      total_value: 275000,
      total_with_addons: 295000,
      prepared_date: '2026-02-10T00:00:00Z',
      valid_until: '2026-03-10T00:00:00Z',
      source: 'referral',
      narrative_context: {
        brandVoice: 'Clean, innovative, human-centered',
        audienceProfile: 'Tech enthusiasts and creative professionals',
        experienceGoal: 'Let consumers feel the magic of spatial computing',
      },
      payment_terms: {
        structure: '50/50',
        depositPercent: 50,
        balancePercent: 50,
      },
      terms_document_id: null,
      tags: ['retail', 'tech', 'demo'],
      portal_access_token: 'tkn_apple_001',
      portal_first_viewed_at: '2026-02-12T09:15:00Z',
      created_by: USER_ID,
      parent_proposal_id: null,
      phase_template_id: 'tmpl_001',
      created_at: '2026-02-01T00:00:00Z',
      updated_at: '2026-02-15T00:00:00Z',
    },
    {
      id: 'prop_005',
      organization_id: ORG_ID,
      client_id: 'client_001',
      name: 'Nike SNKRS Fest 2026',
      subtitle: 'Annual sneaker culture festival and brand activation',
      version: 1,
      status: 'in_production',
      current_phase_id: 'phase_005_05',
      probability: 100,
      currency: 'USD',
      total_value: 425000,
      total_with_addons: 460000,
      prepared_date: '2026-01-15T00:00:00Z',
      valid_until: '2026-02-15T00:00:00Z',
      source: 'referral',
      narrative_context: {
        brandVoice: 'Street culture, authentic, community-driven',
        audienceProfile: 'Sneaker collectors and streetwear enthusiasts',
        experienceGoal: 'Celebrate sneaker culture and drive SNKRS app engagement',
      },
      payment_terms: {
        structure: '50/50',
        depositPercent: 50,
        balancePercent: 50,
      },
      terms_document_id: null,
      tags: ['festival', 'culture', 'large-scale'],
      portal_access_token: 'tkn_nike_002',
      portal_first_viewed_at: '2026-01-18T11:00:00Z',
      created_by: USER_ID,
      parent_proposal_id: null,
      phase_template_id: 'tmpl_001',
      created_at: '2026-01-10T00:00:00Z',
      updated_at: '2026-03-20T00:00:00Z',
    },
    {
      id: 'prop_006',
      organization_id: ORG_ID,
      client_id: 'client_002',
      name: 'Spotify Listening Lounge',
      subtitle: 'Premium artist listening experience at SXSW',
      version: 1,
      status: 'complete',
      current_phase_id: null,
      probability: 100,
      currency: 'USD',
      total_value: 95000,
      total_with_addons: 108000,
      prepared_date: '2025-11-01T00:00:00Z',
      valid_until: '2025-12-01T00:00:00Z',
      source: 'inbound',
      narrative_context: {
        brandVoice: 'Intimate, curated, premium',
        audienceProfile: 'Music industry professionals and influencers',
        experienceGoal: 'Create an exclusive listening experience for emerging artists',
      },
      payment_terms: {
        structure: '50/50',
        depositPercent: 50,
        balancePercent: 50,
      },
      terms_document_id: null,
      tags: ['event', 'music', 'SXSW'],
      portal_access_token: 'tkn_spotify_002',
      portal_first_viewed_at: '2025-11-03T16:45:00Z',
      created_by: USER_ID,
      parent_proposal_id: null,
      phase_template_id: 'tmpl_001',
      created_at: '2025-10-28T00:00:00Z',
      updated_at: '2026-03-15T00:00:00Z',
    },
  ];
}

export function getSeedPhases(proposalId = 'prop_004'): Phase[] {
  return [
    {
      id: `phase_${proposalId}_01`,
      proposal_id: proposalId,
      number: '01',
      name: 'Discovery & Strategy',
      subtitle: 'Research, goals, and creative brief',
      status: 'complete',
      terms_sections: ['1'],
      narrative: 'Define project scope, audience insights, and creative direction.',
      phase_investment: 18000,
      sort_order: 1,
      created_at: '2026-02-01T00:00:00Z',
      updated_at: '2026-02-10T00:00:00Z',
    },
    {
      id: `phase_${proposalId}_02`,
      proposal_id: proposalId,
      number: '02',
      name: 'Concept Design',
      subtitle: 'Visual concepts and spatial planning',
      status: 'complete',
      terms_sections: ['2'],
      narrative: 'Develop experiential concepts, mood boards, and spatial layouts.',
      phase_investment: 32000,
      sort_order: 2,
      created_at: '2026-02-01T00:00:00Z',
      updated_at: '2026-02-20T00:00:00Z',
    },
    {
      id: `phase_${proposalId}_03`,
      proposal_id: proposalId,
      number: '03',
      name: 'Design Development',
      subtitle: 'Detailed design and engineering',
      status: 'in_progress',
      terms_sections: ['3'],
      narrative: 'Refine approved concepts into production-ready specifications.',
      phase_investment: 45000,
      sort_order: 3,
      created_at: '2026-02-01T00:00:00Z',
      updated_at: '2026-03-01T00:00:00Z',
    },
    {
      id: `phase_${proposalId}_04`,
      proposal_id: proposalId,
      number: '04',
      name: 'Fabrication',
      subtitle: 'Build, prototype, and QA',
      status: 'not_started',
      terms_sections: ['4'],
      narrative: 'Fabricate all physical elements, interactive components, and signage.',
      phase_investment: 85000,
      sort_order: 4,
      created_at: '2026-02-01T00:00:00Z',
      updated_at: '2026-02-01T00:00:00Z',
    },
    {
      id: `phase_${proposalId}_05`,
      proposal_id: proposalId,
      number: '05',
      name: 'Technology Integration',
      subtitle: 'AV, interactive, and digital systems',
      status: 'not_started',
      terms_sections: ['5'],
      narrative: 'Install and configure all technology systems and interactive elements.',
      phase_investment: 38000,
      sort_order: 5,
      created_at: '2026-02-01T00:00:00Z',
      updated_at: '2026-02-01T00:00:00Z',
    },
    {
      id: `phase_${proposalId}_06`,
      proposal_id: proposalId,
      number: '06',
      name: 'Logistics & Install',
      subtitle: 'Transport, load-in, and setup',
      status: 'not_started',
      terms_sections: ['6'],
      narrative: 'Coordinate shipping, venue load-in, and on-site installation.',
      phase_investment: 28000,
      sort_order: 6,
      created_at: '2026-02-01T00:00:00Z',
      updated_at: '2026-02-01T00:00:00Z',
    },
    {
      id: `phase_${proposalId}_07`,
      proposal_id: proposalId,
      number: '07',
      name: 'Activation & Staffing',
      subtitle: 'Live event management and operations',
      status: 'not_started',
      terms_sections: ['7'],
      narrative: 'Staff the activation, manage day-of operations, and capture content.',
      phase_investment: 18000,
      sort_order: 7,
      created_at: '2026-02-01T00:00:00Z',
      updated_at: '2026-02-01T00:00:00Z',
    },
    {
      id: `phase_${proposalId}_08`,
      proposal_id: proposalId,
      number: '08',
      name: 'Strike & Wrap',
      subtitle: 'Teardown, reporting, and asset recovery',
      status: 'not_started',
      terms_sections: ['8'],
      narrative: 'Deinstall, return assets to storage, and deliver post-event report.',
      phase_investment: 11000,
      sort_order: 8,
      created_at: '2026-02-01T00:00:00Z',
      updated_at: '2026-02-01T00:00:00Z',
    },
  ];
}
