/**
 * Canonical UI placeholders to ensure SSOT across standard entities and components.
 */

export const WAYFINDING_PLACEHOLDERS = {
  call_time: 'e.g. 3:00 PM — Saturday, March 28',
  route_in: 'e.g. Enter via E 4th Ave and follow event signage...',
  parking: 'Zone B via E 4th Ave...',
  rideshare: 'Rideshare loop on E 32nd St...',
  transit: 'MetroRail Green Line...',
  check_in: 'Proceed to Staff Check-in...',
  checklist: 'e.g., Bring valid photo ID',
  additional_note: 'e.g., Cell service will be unreliable during peak hours...',
  faq_q: 'Question',
  faq_a: 'Answer',
  radio_protocol: 'e.g. Key your radio, wait one second, then speak...',
  safety_rule: 'e.g. No work above 6 feet without fall protection.',
  emergency_code: 'e.g. Code Red',
  emergency_label: 'e.g. Fire / Severe Weather',
  emergency_channel: 'e.g. CH 1 (Emergency)',
  emergency_step: 'e.g. Call "Code Red" on CH 1 with your location...',
  emergency_good_to_know: 'e.g. Fire extinguishers (ABC) are every 75 feet.',
  evacuation_assembly: 'e.g. Parking Zone C',
  evacuation_ems: 'e.g. E 4th Ave entrance',
  evacuation_instructions: 'e.g. Nobody re-enters until All Clear.',
  accessibility_type: 'e.g. ADA Entrance',
  accessibility_description: 'e.g. Accessible entrance at GA gate with ramp...',
  crew_intel_q: 'e.g. Where is the Production Office?',
  crew_intel_a: 'e.g. Turf Lounge, ground floor of VIP Clubhouse...',
  guest_prohibited_item: 'e.g. Weapons or sharp objects',
  guest_bag_policy: 'e.g. Small bags only — 12" × 6" × 12" maximum...',
  guest_re_entry: 'e.g. No re-entry for GA and VIP guests...',
  guest_age_requirements: 'e.g. GA is 18+ and VIP is 21+...',
  guest_dress_code: 'e.g. Smart-casual, comfortable shoes recommended...',
  guest_smoking_policy: 'e.g. Designated areas near parking lot perimeter...',
  sustainability_type: 'e.g. Water Fountains',
  sustainability_description: 'e.g. Free water fountains reduce single-use plastic...',
  external_link_label: 'e.g. Tickets',
  external_link_url: 'e.g. https://dice.fm/event/...',
  social_artist_name: 'e.g. Black Coffee',
  social_handle: 'e.g. @realblackcoffee',
  social_url: 'e.g. https://www.instagram.com/realblackcoffee',
};
